name: Node.js CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 13.x, 14.x, 15.x, 16.x]
    # env:
    #   CODECOV_TOKEN: <___TOKEN___>
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      # - run: npx codecov
      - run: npm i coveralls
      - run: cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
